### ISSUE TITLE
xUnit.net compatible?

### ISSUE THREAD

**Issue by StevenLiekens** [owen2/AutomaticPackageRestoreMigrationScript#17]
xUnit.net's nuget package adds some package restore junk (maybe?) to the csproj files that it is installed into.

```xml
<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
  <PropertyGroup>
    <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
  </PropertyGroup>
  <Error Condition="!Exists('..\..\packages\xunit.core.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.core.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\xunit.core.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.core.props'))" />
</Target>
```
The migration script removes this block from all csproj files that it touches, but I'm not sure if this is actually desirable? Could it potentially break things like Update-Package when a newer version of xUnit.net becomes available? Maybe MSBuild *should* fail when the package is not found?

**Comment by owen2** [comment]
I don't think xunit should be doing that to your projects. VS or TFS or `nuget.exe restore` will still restore packages even with this removed. Xunit adding this to your project could actually end up breaking your projects. I'll try to look into this a bit more later.

**Comment by StevenLiekens** [comment]
It turns out that this is not at all specific to xunit.

When you author a package that contains one (or both) of:
 - `build\{packageid}.props`
 - `build\{packageid}.targets`

NuGet automatically adds imports to projects that you install the package into.
 - `<Import Project="..\packages\BuildPackage.1.0.0\build\BuildPackage.props" Condition="Exists('..\packages\BuildPackage.1.0.0\build\BuildPackage.props')" />`
 - `<Import Project="..\packages\BuildPackage.1.0.0\build\BuildPackage.targets" Condition="Exists('..\packages\BuildPackage.1.0.0\build\BuildPackage.targets')" />`

NuGet also adds an extra target named `EnsureNuGetPackageBuildImports`. 
```xml
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\BuildPackage.1.0.0\build\BuildPackage.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\BuildPackage.1.0.0\build\BuildPackage.props'))" />
    <Error Condition="!Exists('..\packages\BuildPackage.1.0.0\build\BuildPackage.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\BuildPackage.1.0.0\build\BuildPackage.targets'))" />
  </Target>
```

This is completely automatic and inevitable.

**Comment by owen2** [comment]
Does removing the section break xunit?

**Comment by StevenLiekens** [comment]
It doesn't break xunit (or other packages) because the `<Import />` elements are left intact.

The only thing `EnsureNuGetPackageBuildImports` does is fail the build early and print a friendly message when the files in the `<Import />` elements are missing. It doesn't hurt to remove it.
