### ISSUE TITLE
out-file is producing two empty new lines at the end of csproj file in fixHintPath.ps1

### ISSUE THREAD

**Issue by sharifmamun** [owen2/AutomaticPackageRestoreMigrationScript#28]
I get two empty new lines at the end of the csproj files, why don't we use `[IO.File]::WriteAllText()` instead of out-file so that we can get rid of the new lines issue. Is there any particular reason of not using `[IO.File]::WriteAllText()`?

**Comment by Itfly** [comment]
I solve this problem by modifying the fixHintPath.ps1 same as: https://github.com/owen2/AutomaticPackageRestoreMigrationScript/commit/ada11afcdcc5ccc26d8a42cea10be82f53ced2fc
