### ISSUE TITLE
Entry point?

### ISSUE THREAD

**Issue by mrchief** [owen2/AutomaticPackageRestoreMigrationScript#7]
It'd help to leave a note about each script and its purpose, as well as when to run what.

This is a great time saver otherwise!!

**Comment by owen2** [comment]
I added some more documentation. It used to be all one script, and I never fixed the readme after i had split it. Take a look now and let me know if things are still unclear. 

Thanks for opening an issue!

**Comment by mrchief** [comment]
:+1:
