### ISSUE TITLE
Script doesn't remove <RestorePackages> line from project files.

### ISSUE THREAD

**Issue by bpeikes** [owen2/AutomaticPackageRestoreMigrationScript#9]
According to the article that you based the script on, you're supposed to remove the <RestorePackages>true</RestorePackages> line from project files. It seems to be missing from the list of regular expressions.

**Comment by owen2** [comment]
I don' think I've encountered those lines in any project files, could you please post an excerpt from a proj file so I can look into it and potentially add it to the script?

**Comment by bpeikes** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="
http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == ''
">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>9.0.30729</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{7BD44ED5-3085-483A-B144-E3FDCA4F5548}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>

<RootNamespace>TrilliumLabs.Surveyor.Services.Authentication</RootNamespace>

<AssemblyName>TrilliumLabs.Surveyor.Services.Authentication</AssemblyName>
    <TargetFrameworkVersion>v4.5.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <UpgradeBackupLocation>
    </UpgradeBackupLocation>
    <OldToolsVersion>3.5</OldToolsVersion>
    <TargetFrameworkProfile />
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) ==
'*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' ==
'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' ==
'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net, Version=1.2.13.0, Culture=neutral,
PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>

<HintPath>..\packages\log4net.2.0.3\lib\net40-full\log4net.dll</HintPath>
    </Reference>
    <Reference Include="MySql.Data, Version=6.8.3.0, Culture=neutral,
PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>

<HintPath>..\packages\MySql.Data.6.8.3\lib\net45\MySql.Data.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=6.0.0.0, Culture=neutral,
PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>

<HintPath>..\packages\Newtonsoft.Json.6.0.4\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.DirectoryServices.AccountManagement" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.IdentityModel.Selectors" />
    <Reference Include="System.Runtime.Serialization">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.ServiceModel">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.ServiceModel.Activation" />
    <Reference Include="System.ServiceModel.Web">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Xml.Linq">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AuthenticationException.cs" />
    <Compile Include="AuthenticationService.cs" />
    <Compile Include="AuthMapping.cs" />
    <Compile Include="AuthMappingService.cs" />
    <Compile Include="AuthorizationException.cs" />
    <Compile Include="AuthProvider.cs" />
    <Compile Include="AuthProviderService.cs" />
    <Compile Include="AuthToken.cs" />
    <Compile Include="AuthTokenLog.cs" />
    <Compile Include="AuthTokenLogService.cs" />
    <Compile Include="AuthTokenSevice.cs" />
    <Compile Include="AuthType.cs" />
    <Compile Include="AuthTypeService.cs" />
    <Compile Include="CustomUserNamePasswordValidator.cs" />
    <Compile Include="DatabaseAuthenticationService.cs" />
    <Compile Include="IAuthenticationService.cs" />
    <Compile Include="Exceptions.cs" />
    <Compile Include="IUserAuthentication.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="User.cs" />
    <Compile Include="UserContext.cs" />
    <Compile Include="UserGroup.cs" />
    <Compile Include="UserGroupService.cs" />
    <Compile Include="UserGroupUser.cs" />
    <Compile Include="UserGroupUsersService.cs" />
    <Compile Include="UserService.cs" />
    <Compile Include="WCFAuthenticator.cs" />
    <Compile Include="WindowsAuthenticationService.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Databases\Databases.csproj">
      <Project>{96698C36-472F-44A7-9581-EC1E58B5DE4B}</Project>
      <Name>Databases</Name>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Project>{DEF21816-DBEE-41D4-A65D-5E365E73D03D}</Project>
      <Name>Utilities</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="$(SolutionDir)\.nuget\NuGet.targets"
Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports"
BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing
on this computer. Enable NuGet Package Restore to download them.  For more
information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing
file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')"
Text="$([System.String]::Format('$(ErrorText)',
'$(SolutionDir)\.nuget\NuGet.targets'))" />
  </Target>
  
</Project>

**Comment by owen2** [comment]
Thanks for the csproj file, I'm going to do some research and double check to see if those are supposed to be there or not!

**Comment by jochenvanwylick** [comment]
I think @bpeikes is correct and that they need to go. At least. that's what I got from: http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore .

Thanks for the script - I ran it over 60 + projects works like a charm. After that I removed that <RestorePackages> line.

**Comment by owen2** [comment]
Yup, looks like VS adds these lines to enable/disable the old package restore, going to add it to the script now.

**Comment by downerboy** [comment]
Thank you for making my life easier!  May the gods bless with lots of everything that makes you happy!
